### ISSUE TITLE
Sample quiz data is not valid.

### ISSUE THREAD

**Issue by MichaelKentBurns** [AshDest/front-end_quiz_app#1]
When I tested out your quiz I was concerned because I was getting "wrong" alerts on questions that I have good knowledge of.  Then I looked at your quiz data and realized that it was not valid questions.      One of the things that this tells me is that you did not really fully test your app even though it was a trivial example.   One of my rules of thumb is "Never push code that has not been tested even if you know it is correct."

**Comment by AshDest** [comment]
Of course these questions are not logical. 
The initial idea of this project is to link it to a backend (i.e. to a database) which will be able to store the questions and the score each time.
This is only a product example, however the project could evolve to become a theoretical exercise platform for new developers.

**Comment by AshDest** [comment]
now I modified the questions that were there initially, because they were just test questions.
but the objective of these application is that we continue to raise other questions related to frontend developers to measure our level of understanding of the lesson
