### ISSUE TITLE
Every repository should have a README.md to at least explain it's existence.

### ISSUE THREAD

**Issue by MichaelKentBurns** [AshDest/front-end_quiz_app#4]
Yes, you do have a README.md but it does not have many of the features that READMEs should have.   

See [this article from GitHub:](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes)

**Comment by AshDest** [comment]
I reviewed my readme file according to the advice given

**Comment by MichaelKentBurns** [comment]
Excellent correction.   This makes your repository much more interesting and useful.  
Just like your Upwork profile is the front door to getting work,  your repositories README.md is the front door to getting your code seen, used and showing your professionalism.

**Comment by MichaelKentBurns** [comment]
+1
Good fix!
